# Database Configuration
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5437/course_evaluation
db.username=jackson
db.password=jackson123

# Mail Configuration (update with your SMTP details)
mail.host=smtp.gmail.com
mail.port=465
mail.username=jacksonbimenyimana3@gmail.com
mail.password=xzii oece vfxt nmuu
